-- 0004_node_geo.sql: global node scheduling support

ALTER TABLE nodes ADD COLUMN region TEXT DEFAULT '';
ALTER TABLE nodes ADD COLUMN country TEXT DEFAULT '';
ALTER TABLE nodes ADD COLUMN city TEXT DEFAULT '';
ALTER TABLE nodes ADD COLUMN latitude REAL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN longitude REAL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN max_connections INTEGER DEFAULT 100;
ALTER TABLE nodes ADD COLUMN weight REAL DEFAULT 1.0;
ALTER TABLE nodes ADD COLUMN is_active INTEGER DEFAULT 1;

CREATE TABLE IF NOT EXISTS node_health (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  node_id INTEGER NOT NULL,
  latency_ms INTEGER DEFAULT 0,
  current_connections INTEGER DEFAULT 0,
  cpu_load REAL DEFAULT 0,
  memory_usage REAL DEFAULT 0,
  bandwidth_mbps REAL DEFAULT 0,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
);
