// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';

export function CreateNode(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreateProxy(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function DiscoverPorts():Promise<Array<discovery.PortInfo>>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetServerURL():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function ListNodes():Promise<Array<Record<string, any>>>;

export function ListProxies():Promise<Array<Record<string, any>>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function QuickTunnel(arg1:string,arg2:number,arg3:number):Promise<number>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartProxy(arg1:number):Promise<void>;

export function StopProxy(arg1:number):Promise<void>;
