// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNode'](arg1, arg2, arg3);
}

export function CreateProxy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProxy'](arg1, arg2, arg3, arg4);
}

export function DiscoverPorts() {
  return window['go']['main']['App']['DiscoverPorts']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListProxies() {
  return window['go']['main']['App']['ListProxies']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function QuickTunnel(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuickTunnel'](arg1, arg2, arg3);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy(arg1) {
  return window['go']['main']['App']['StopProxy'](arg1);
}
